baseURL = 'https://snippets.eddy.rest'
languageCode = 'en-us'
title = 'Code Snippets'

theme = 'archie'

copyright = "Eddy22"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="auto" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Collection of code snippets frequently used by eddy22"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/adnanyousef"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/adnanyousef/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
